2018-01-20 21:31:53 [ERROR] - Log -Log.java(41)  -setup
2018-01-20 21:31:53 [ INFO] - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-20 22:16:56 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-20 22:16:57 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:05 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomLimit
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomLimit2
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomAdd
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=33,author=陈其瑞  ,chaodai=清  ,name=本草撮要,about= ,file_name=032-本草撮要.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomSQL
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[author=陈其瑞  ,name=本草撮要]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:55 [ERROR]-main - Log -Log.java(41)  -testCustomLimit
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustomAdd
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=33,author=陈其瑞  ,chaodai=清  ,name=本草撮要,about= ,file_name=032-本草撮要.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustomSQL
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[author=陈其瑞  ,name=本草撮要]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:09:21 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:11:08 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:11:09 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:11:53 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:11:59 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:14:14 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:14:19 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:15:19 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:15:24 [ INFO]-main - Log -Log.java(30)  -5
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -1
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -1
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:45 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:53 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:54 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:23:09 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:23:10 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:45:33 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:45:34 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:46:15 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:46:16 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:46:45 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:46:45 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:17 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -m = null
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -test update
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -1
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testDel
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testGet
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testAll
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -testEq
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -1
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:24 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:54 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 1,本草_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 2,方剂_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 3,医案_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 4,经论_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 5,专科_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '5' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 7,炮制_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '7' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 8,针灸_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '8' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 9,五运六气_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '9' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 10,诊断_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '10' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 11,养生_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '11' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 12,周易_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '12' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 13,六爻_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '13' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 14,风水_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '14' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 15,房事_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 16,佛道_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '16' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 17,相术_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '17' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 18,八字_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '18' for key 1
	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:08:04 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:11:10 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:16:24 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:16:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:16:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `select`() values() ,param = 
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:204)
	at org.docshare.orm.DBTool.save(DBTool.java:178)
	at org.docshare.orm.Model.save(Model.java:347)
	at org.docshare.test.TestORMFoo.testInsert(TestORMFoo.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.docshare.orm.DBHelper.getPrepareRS(DBHelper.java:115)
	at org.docshare.orm.mysql.MySQLDelegate.resultById(MySQLDelegate.java:24)
	at org.docshare.orm.DBTool.get(DBTool.java:125)
	at org.docshare.orm.DBTool.get(DBTool.java:114)
	at org.docshare.test.TestORMFoo.testUpdate(TestORMFoo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -exec sql fail delete from `select` where `ss` = ? ,param = 0
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.DBHelper.update(DBHelper.java:190)
	at org.docshare.orm.mysql.MySQLDelegate.delete(MySQLDelegate.java:98)
	at org.docshare.orm.DBTool.del(DBTool.java:259)
	at org.docshare.test.TestORMFoo.testRemove(TestORMFoo.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.docshare.orm.DBHelper.getPrepareRS(DBHelper.java:115)
	at org.docshare.orm.mysql.MySQLDelegate.resultById(MySQLDelegate.java:24)
	at org.docshare.orm.DBTool.get(DBTool.java:125)
	at org.docshare.orm.DBTool.get(DBTool.java:114)
	at org.docshare.test.TestORMFoo.testRemove(TestORMFoo.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:39:05 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
